# Generated by Django 5.1.6 on 2026-05-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_poem_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='STANZA',
            field=models.TextField(),
        ),
    ]
