# Generated by Django 5.1.6 on 2026-05-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_poem_stanza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
